VPATH=.:../Include:../Insert:../Delete:../Search:../Reverse:../Other
obj=main.o insert_head.o insert_tail.o insert_pos.o\
	delete_head.o delete_tail.o  delete_pos.o\
	search.o reverse.o initlist.o show.o
main:$(obj)
	gcc -o main $(obj)

main.o:
initlist.o:
insert_head.o:
insert_tail.o:
insert_pos.o:
delete_head.o:
delete_tail.o:
delete_pos.c:
search.o:
reverse.o:
show.o:

clean:
	rm *.o main
